name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository, so the workflow can access the files
      - uses: actions/checkout@v3
        with:
          # Fetches all history for all branches and tags, which is necessary for pushing
          fetch-depth: 0

      - name: Add remote
        env:
          HF: ${{secrets.HF}}
        run: git remote add space https://abdelrahman-alkhodary:$HF@huggingface.co/spaces/abdelrahman-alkhodary/demo

      # Step 2: Push the code to the Hugging Face Space repository
      - name: Push to hub
        env:
          # The Hugging Face token is stored as a secret in the GitHub repository settings
          HF: ${{ secrets.HF }} 
        run: git push --force https://abdelrahman-alkhodary:$HF@huggingface.co/spaces/abdelrahman-alkhodary/demo main
